runner:
  total_steps: 350000
  gradient_clipping: 1.0
  gradient_accumulate_steps: 1

  log_step: 1750
  eval_step: 1750
  save_step: 8750
  max_keep: 100
  eval_dataloaders:
    - dev

optimizer:
  name: AdamW
  lr: 1.e-3

downstream_expert:
  datarc:
    num_speakers: 1
    rate: 16000
    src: ['mix_single']
    tgt: ['s1']
    n_fft: 512
    win_length: 512
    window: "hann"
    center: True

  loaderrc:
    num_workers: 4
    train_batchsize: 8
    eval_batchsize: 1
    train_dir: ./s3prl/downstream/enhancement_stft/data/wav16k/min/train-100
    dev_dir: ./s3prl/downstream/enhancement_stft/data/wav16k/min/dev
    test_dir: ./s3prl/downstream/enhancement_stft/data/wav16k/min/test
  
  modelrc: 
    model: SepRNN
    rnn: LSTM
    rnn_layers: 3
    hidden_size: 896
    dropout: 0.5
    non_linear: relu
    bidirectional: True
    loss_type: MSE
    mask_type: NPSM
