runner:
  total_steps: 500000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 5000
  eval_step: 10000
  save_step: 10000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.e-4

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 32 
    eval_batch_size: 32
    libri_root: '/work/a129195789/LibriSpeech/'
    phone_path: './downstream/phone_linear/data'
    bucket_file: 'data/len_for_bucket'
    sample_rate: 16000 # this should not be changed, and this should match the sr of the audio in `libri_root`
    train_dev_seed: 1337

  modelrc: 
    none: None